name: doctopia_helper_server
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  conduit: ^4.3.7
  conduit_core: ^4.3.6
  equatable:
  dart_appwrite:

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^4.3.6
